### ISSUE TITLE
backuppc 4 & Debian

### ISSUE THREAD

**Issue by trentasis** [backuppc/backuppc#206] opened 2018-07-01 09:23 UTC
Latest backuppc version +4 are not available from debia, any scheuled date when will be available in official repositorires?

https://packages.debian.org/buster/backuppc
https://packages.debian.org/stretch/backuppc
https://packages.debian.org/sid/backuppc

Thanks

**Comment by trentasis** [comment] 2018-07-09 17:18
Hi,

Any scheduled date when will be available to debian repositories?
Thanks

2018-07-09 16:41 GMT+02:00 Craig Barratt <notifications@github.com>:

**Comment by dbrazziel** [comment] 2018-07-26 00:16
When building rsync-bpc I got a fatal error that said debian/tmp conffiles was not in the control file or some such.

**Comment by raoulbhatia** [comment] 2018-07-26 05:21
@trentasis I wouldn't know of any ETA, sorry

@dbrazziel please file a bug against https://github.com/raoulbhatia/rsync-bpc/ where I am maintaining the Debian related files

**Comment by dbrazziel** [comment] 2018-07-26 12:11
Do I file against rsync proper (https://rsync.samba.org/bugzilla.html) or in the rsync-bpc area? If the latter, how do I open a new issue?

**Comment by raoulbhatia** [comment] 2018-07-27 05:57
It would be `rsync-bpc` as "vanilla" rsync is already available in Debian, mir specifically the repository you build from

However, I've disabled issue tracking in my repo... :-)
Can you please share the output via a gist or pastebin?

Thanks,
Raoul

Can you

**Comment by dbrazziel** [comment] 2018-07-28 15:09
OK, I logged the output and put it on pastebin here:

https://pastebin.com/pqGwXSKU

**Comment by dbrazziel** [comment] 2018-07-30 20:00
I am on Debian testing / unstable distribution. 

cat /etc/issue
Debian GNU/Linux buster/sid \n \l

Yes, I followed the 'Build-Your-Own-Packages' directions. backuppc-xs and backuppc got clean builds and produced .deb packages, but rsync-bpc build failed per the above log

**Comment by raoulbhatia** [comment] 2018-07-31 13:47
I am sorry but I am not able to reproduce this.  I even created a Dockerfile (not how you normally use Docker, I know) and can perfectly build this packages, see https://gist.github.com/raoulbhatia/00141b74cd4b27f95f14ac31a27090b9

I'll share the .deb files for you to test shortly.

Raoul

**Comment by raoulbhatia** [comment] 2018-07-31 13:52
Please try:
* https://s3-eu-west-1.amazonaws.com/backuppc4/Debian10/backuppc-xs_0.57_amd64.deb
* https://s3-eu-west-1.amazonaws.com/backuppc4/Debian10/backuppc_4.2.1_amd64.deb
* https://s3-eu-west-1.amazonaws.com/backuppc4/Debian10/rsync-bpc_3.0.9.12_amd64.deb

**Comment by dbrazziel** [comment] 2018-07-31 13:59
Thank you very much. I deleted the rsync-bpc directory and gave it another shot, but no joy. Thanks again for your work on this, it is much appreciated.

**Comment by raoulbhatia** [comment] 2018-08-02 07:57
I've linked the packages in https://github.com/backuppc/backuppc/wiki/Build-Your-Own-Packages and have also shared the Dockerfile to help people build their packages.

@craigbarratt please close this issue.

**Closed** 2018-08-02 15:19 UTC

**Comment by jupsoleil** [comment] 2019-06-12 13:35
Hi, I'm sorry, this issue gets closed, but without reply to the question when we may expect packages in official repositories.

**Comment by raoulbhatia** [comment] 2019-06-12 13:47
This has to be handled via Debian's process and its bug tracker, i.e. https://bugs.debian.org/backuppc

I've tried to contribute to the packages via https://salsa.debian.org/debian/libbackuppc-xs-perl/merge_requests/ but it is still lacking a review & merge.  I figure I would need to go through the regular process of becoming a Debian contributor, which I currently do not have time for.

Adding @xtaran for visibility.

**Comment by cpaelzer** [comment] 2019-10-17 09:00
The former mentioned [open MRs](https://salsa.debian.org/debian/libbackuppc-xs-perl/merge_requests/?scope=all&utf8=%E2%9C%93&state=all) are resolved by now I think as the MR queue is empty atm.

Still leaved backuppc4 itself being open. FYI the official Debian bug for that is [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873075) and Ubuntu [here](https://bugs.launchpad.net/backuppc/+bug/1723392)
