### ISSUE TITLE
Empty (zero bytes) zip/tar files on restore

### ISSUE THREAD

**Issue by basg** [backuppc/backuppc#156] opened 2017-10-03 17:52 UTC
When restoring files through the web-interface as .zip or .tar archives, we are getting empty/zero-byte archives. I believe this issue was adressed in #128 and should be fixed, but it seems to still occur in our setup. 

BackupPC version:  4.1.3 / CentOS 7

**Comment by hobbes1069** [comment] 2017-10-03 17:53
Was the commit part of the 4.1.3 release or does it need to be added as a patch?

**Comment by prupert** [comment] 2017-10-03 17:59
The 4.1.3 rpm release seems to be from before the bug fixes were committed to master. (It is a bit confusing that version info in comments was changed during these commits.)

From the 4.1.3 package:
```
* Sun Jun 04 2017 Richard Shaw <hobbes1069@gmail.com> - 4.1.3-1
- Update to latest upstream release.
```

The commits 0439411cc17757e5f15ebfbff902aacc3d4510b6 and 6f01264005310cffe55d5258436d38609a1ac99d are from 30-Jul-2017.

**Comment by prupert** [comment] 2017-10-03 18:00
@hobbes1069 - can you release a new `-2` package with the patch applied?

**Comment by hobbes1069** [comment] 2017-10-03 18:16
The first commit is part of the 4.1.3 release, the second does not apply cleanly. I'll have to see how easy it would be to apply manually.

**Comment by hobbes1069** [comment] 2017-10-03 18:25
Ok, figured it out.

**Comment by hobbes1069** [comment] 2017-10-03 18:35
Can you test the following package and make sure it works? I don't want to build for Fedora or on COPR if it breaks something else.

https://hobbes1069.fedorapeople.org/BackupPC-4.1.3-3.fc26.src.rpm

**Comment by prupert** [comment] 2017-10-03 18:56
Just curious, what patch did you end up applying in the package? I will try to get a test box soon.

**Comment by basg** [comment] 2017-10-16 13:29
Thanks for supplying a patched package!
Unfortunately, the fix doesn't seem to change anything. 
Upon restoring a path to a zip (or tar) archive of a certain path, backuppc still serves up a 0 byte archive.

**Comment by nauevg** [comment] 2017-10-19 04:21
Hello. Also having zero bytes in zip/tar. Any news?

**Comment by prupert** [comment] 2017-10-19 11:45
@hobbes1069 updating to `BackupPC-4.1.3-3.el7.centos.x86_64.rpm` did not resolve the issue unfortunately

**Comment by hobbes1069** [comment] 2017-10-19 13:15
I'm on vacation through the weekend but as far as I know the patches were applied.

**Comment by prupert** [comment] 2017-11-02 09:45
@hobbes1069: hope you had a great vacation. 

The issue still persists on our systems after upgrading.

**Comment by hobbes1069** [comment] 2017-11-02 12:28
Since we're dealing with Perl and you're familiar with the commits referenced above, can you verify they have been applied in your installed package? I know I applied the patch...

**Comment by mgutierrezp** [comment] 2017-11-03 09:53
I'm also suffering this bug. Patches didn't solve it

**Comment by basg** [comment] 2017-11-03 11:52
I can confirm the patches were applied in the package. The problem persists.

**Comment by hobbes1069** [comment] 2017-11-03 16:30
I tried creating a zip archive from the command line and it worked so I'm guessing the problem is with the CGI interface somehow...

**Comment by craigbarratt** [comment] 2017-11-05 17:27
The original problem was a perl tainting issue (specific to CGI/Apache as Richard mentions), which should have been fixed by the commits that Richard applied.  Can someone with the problem email me their bin/BackupPC_tarCreate and/or bin/BackupPC_zipCreate files?

As a workaround, you should be able to use these commands from the command-line to create tar or zip archives of any backup.

**Comment by craigbarratt** [comment] 2017-11-05 17:49
Another thing to test is the following.  Edit the first line of BackupPC_tarCreate to add a -T option to perl, eg:
```
#!/usr/bin/perl -T
```
Then run BackupPC_tarCreate (as the backuppc user) from the command line, eg:
```
BackupPC_tarCreate -h HOST -s SHARE -n -1 /some/backup/path/to/a/file > /dev/null
```
What error output (if any) do you get?

**Comment by basg** [comment] 2017-11-06 10:48
I've tested this command, hopefully this is helpful to you: 
```
/usr/share/BackupPC/bin/BackupPC_tarCreate -h hostname.redacted.tld -s / -n -1 /filename/redacted > /dev/null

No language setting
BackupPC::Lib->new failed
```

**Comment by craigbarratt** [comment] 2017-11-08 07:04
Thanks for sending the two files.  The patches have been applied correctly.

However, the "No language setting" error means the something is misconfigured, in particular reading the config.pl file didn't work.

Do other utilities (that were not patched) get that error too, eg:
```
BackupPC_ls
```
Does it print the same "No language setting" error (bad), or does it print usage info (ok)?

**Comment by basg** [comment] 2017-11-09 15:59
@craigbarratt, I'm sorry to say I've made a slight mistake in performing these tests, I executed the commands as another user than `BackupPC`. This may have yielded some unreliable test results. 

When I'm logged in as the BackupPC user the command `/usr/share/BackupPC/bin/BackupPC_tarCreate -h hostname.redacted.tld -s / -n -1 /filename/redacted > /dev/null` executes with no errors, returning exit code 0. 
Using the `-T` option in the perl shebang makes no difference.

**Comment by hobbes1069** [comment] 2017-11-09 16:02
So basically the same as my experience. It works from the command line but not from the CGI interface. I actually redirected the output to a file and verified it was a valid zip file.

**Comment by basg** [comment] 2017-11-09 16:43
Some more tests; Since we applied the patches, creating tar files worked fine. Creating zip-files still doesn't. 
Here are some tests with creating zipfiles from the command line, executed with the correct user (`backuppc`): 
`$ /usr/share/BackupPC/bin/BackupPC_zipCreate -h hostname.redacted.tld -s / -n -1 /some/file/path > /dev/null`:
```
Can't locate BackupPC/Lib.pm in @INC (@INC contains: /usr/local/BackupPC/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/BackupPC/bin/BackupPC_zipCreate line 67.
BEGIN failed--compilation aborted at /usr/share/BackupPC/bin/BackupPC_zipCreate line 67.
```

**Comment by hobbes1069** [comment] 2017-11-09 17:02
@basg can you post these variables from your /etc/BackupPC/config.pl?
```
$Conf{TopDir} = '/var/lib/BackupPC/';
$Conf{ConfDir} = '/etc/BackupPC/';
$Conf{LogDir} = '/var/log/BackupPC';
$Conf{RunDir} = '/var/run/BackupPC';
$Conf{InstallDir} = '/usr/share/BackupPC';
$Conf{CgiDir} = '/usr/libexec/BackupPC';
```

**Comment by basg** [comment] 2017-11-09 18:29
Certainly;
```
$Conf{TopDir} = '/var/lib/BackupPC/';
$Conf{ConfDir} = '/etc/BackupPC/';
$Conf{LogDir} = '/var/log/BackupPC';
$Conf{RunDir} = '/var/run/BackupPC';
$Conf{InstallDir} = '/usr/share/BackupPC';
$Conf{CgiDir} = '/usr/libexec/BackupPC';
```

**Comment by hobbes1069** [comment] 2017-11-09 18:52
Well, darn. Same as mine. I was hoping it was something simple since your's seems to be having trouble finding the Lib perl module and mine CentOS 7 box isn't...

**Comment by hobbes1069** [comment] 2017-11-09 18:53
How did you become the backuppc user? I use:
```
su -s /bin/bash -l backuppc
```

**Comment by basg** [comment] 2017-11-09 19:17
I became `backuppc` through `su -s /bin/bash - backuppc`. 

According to the error message, `BackupPC/Lib.pm` couldn't be found in Perl's search paths..
```
Can't locate BackupPC/Lib.pm in @INC
(@INC contains: /usr/local/BackupPC/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .)
```
It exists, but on another location; `/usr/share/BackupPC/lib/BackupPC/Lib.pm`

**Comment by hobbes1069** [comment] 2017-11-09 19:22
I'm not sure if the "-l" makes a difference or not, but it doesn't make sense that mine works and yours doesn't...

**Comment by basg** [comment] 2017-11-09 19:36
When i compare the `zipCreate` and `tarCreate` files, 
it becomes clear that a wrong path is used in `zipCreate` to import the library from the snippets below:     

`zipCreate` (doesn't work): 
```
     59 use strict;
     60 no  utf8;
     61 use lib "/usr/local/BackupPC/lib";
     62 use Archive::Zip qw(:ERROR_CODES);
     63 use File::Path;
     64 use Getopt::Std;
     65 use Encode qw/from_to/;
     66 use IO::Handle;
     67 use BackupPC::Lib;
     68 use BackupPC::XS qw( :all );
     69 use BackupPC::Zip::FileMember;
     70 use BackupPC::View;
```
vs `tarCreate` (works);
```
     64 no  utf8;
     65 use lib "/usr/share/BackupPC/lib";
     66 use File::Path;
     67 use Getopt::Std;
     68 use Encode qw/from_to/;
     69 use Data::Dumper;
     70
     71 use BackupPC::Lib;
     72 use BackupPC::XS qw( :all );
     73 use BackupPC::View;
```

**Comment by hobbes1069** [comment] 2017-11-09 19:51
Found it... I did an sdiff between the two files, tarCreate (left) uses a variable which is substituted during install, zipCreate (right) has it statically set:
```
use lib "__INSTALLDIR__/lib";                                 | use lib "/usr/local/BackupPC/lib";
```

**Comment by basg** [comment] 2017-11-09 19:54
Great! We'll be glad to test another patched package. Thanks in advance for your effort!

**Comment by hobbes1069** [comment] 2017-11-09 19:55
I still have the problem of zero size using the CGI so this may only fix the command line problem...

**Comment by basg** [comment] 2017-11-09 20:00
I guess i got excited too soon, but please let me know if I can be of any assistance.

**Comment by hobbes1069** [comment] 2017-11-09 20:01
It would be good to confirm if this at least fixed the command line problem...

https://www.dropbox.com/s/yyzojnzff1d6a1k/BackupPC-4.1.3-4.el7.centos.x86_64.rpm

**Comment by basg** [comment] 2017-11-10 15:24
It looks like the latest patch solves the problem through both the command line and CGI on our setup. 
I have been testing this with modestly sized archives of several MB's. 
Tests with larger (several GBs) seem to fail, but with different symptoms (the connection just times out instead of serving an empty file), so i'm unsure if those failures are related to this particular problem. 
I will do some additional research and post back with my findings.

**Comment by craigbarratt** [comment] 2017-11-12 23:41
Thanks for the updates.  Does anyone have correctly patched and correctly installed (ie, correct paths) that still fail with CGI tar/zip restore?  If not, I'll close the issue.

**Comment by basg** [comment] 2017-11-13 14:05
Can we expect a new package containing these fixes through the official repos?

**Comment by hobbes1069** [comment] 2017-11-13 14:06
I'm still having trouble from the CGI interface, both ZIP and TAR are 0 size, but works from the command line. Since I seem to be the only one with this issue maybe close this one and open a new issue?

**Comment by mgutierrezp** [comment] 2017-11-15 08:36
Hi all,

After inspecting the rpm hobbes1069 attached, I've changed the following line in BackupPC_zipCreate and BackupPC_tarCreate:


use lib "/usr/local/BackupPC/lib";
by
use lib "/usr/share/BackupPC/lib";

This has definitely worked for me. Please check.
Before applying this change, the command line only worked for me after changing PERL5LIB env variable to /usr/share/BackupPC/lib, so this makes sense.

**Comment by craigbarratt** [comment] 2017-11-20 01:15
@basg Hopefully I'll release a new version over the US Thanksgiving holidays (next weekend).

**Comment by craigbarratt** [comment] 2017-11-25 19:53
@hobbes1069 - I just released 4.1.4.  Can you try starting with the tarball and seeing if you still have the issue?

**Comment by hobbes1069** [comment] 2017-11-25 21:19
Don't know what was missing from my patch but that fixed it!

**Comment by craigbarratt** [comment] 2017-12-03 00:45
Great - thanks for everyone's help.  Closing the issue.

**Closed by craigbarratt** 2017-12-03 00:45 UTC
