### ISSUE TITLE
BackupPC 4.1.2 loses Conf{BackupFilesExclude} on the interface

### ISSUE THREAD

**Issue by johanehnberg** [backuppc/backuppc#117] opened 2017-05-18 06:59 UTC
The following (or more exclude rows) in config.pl:
```
$Conf{BackupFilesExclude} = {
  '*' => [
    '/proc'
  ]
};
```

Is not picked up by the UI properly, and only an asterisk is shown for the share name. Saving it becomes:
```
$Conf{BackupFilesExclude} = {
  '*' => []
};
```

This happens both if the config was generated by the UI or written by hand.

**Comment by craigbarratt** [comment] 2017-05-18 16:10
This is a duplicate of #112.  It was fixed with this push: https://github.com/backuppc/backuppc/commit/7936184a9ec049fef3d0d67e012b23d79eb336f1.

**Closed** 2017-05-20 03:43 UTC
