### ISSUE TITLE
BackupFilesOnly

### ISSUE THREAD

**Issue by AlexeySaff** [backuppc/backuppc#119] opened 2017-05-21 14:15 UTC
after updating to 4.1.2 from 4.1.1 find that we had huge problem with BackupFilesOnly

check for previous messages and it seems that fix <7936184> doesn't work

in my log i can see 
2017-05-19 10:22:15 admin changed BackupFilesOnly in main config to {'/' => [],'/home' => []} from {'/' => ['/etc','/root'],'/home' => ['/*/[dD]ev','/*/[dD]evelopment','/*/[Ww]orkspace*','/*/[Pp]rojects*','/*/svn/','/*/.*','/*/www/','/*/script*']}

and now can't edit those settings via web interface

**Comment by craigbarratt** [comment] 2017-05-21 16:37
This is a duplicate of #112. It is fixed in master with this push: 7936184.

**Closed** 2017-05-21 16:37 UTC
