### ISSUE TITLE
backuppc-3.3.1 is incompatible with Samba Samba 4.3.9

### ISSUE THREAD

**Issue by maksyms** [backuppc/backuppc#21] opened 2016-08-13 14:19 UTC
Upgraded to Ubuntu 16.04.1 LTS with backuppc-3.3.1 and samba 4.3.9 installed from distribution. Since then, no backups over smb work. The reason seems to be a change in smbclient output that Smb.pm is unaware of. I'm checking whether [this](https://bugzilla.redhat.com/attachment.cgi?id=1111264) fixes it. If it does, I'll create a patch and a pull request into master.

**Comment by maksyms** [comment] 2016-08-14 00:23
It does look like it is properly broken. Samba 4 does not produce the same output as Samba 3 that BackupPC uses to count files in the backup, not even close. Unless smbclient can be made to produce similar output, only downgrading smbclient may work.

**Comment by maksyms** [comment] 2016-08-14 07:19
So more information:
smbclient 3.3 produces lines like:

                directory \$RECYCLE.BIN\
                directory \OneDriveTemp\
                directory \OneDriveTemp\S-1-5-21-604785434-3978931842-3537929524-1000\
                directory \System Volume Information\


and


                 1689 (  329.9 kb/s) \Users\test\Documents\Adobe\Premiere Elements\8.0\CAObjectTrackResults\MVI_0468_0_413\ObjectTrack.log

at debug level 0.

smbclient-4.3.9 does not produce anything even similar, until a very noisy debug level 5, where you can see this:

                tar:899  +++ \usr\local\wbin\tail.exe

As a result, Smb.pm does not see any files being transferred, despite BackupPC_tarExtract successfully finding and extracting all of them!

The fix is not trivial.

1. Either modify smbclient-4.3.9, file source3/client/clitar.c in the routine tar_get_file around line 899 to produce output similar to smbclient-3.3
2. Or rewrite code in Smb.pm to extract full byteCnt from smbclient output (possible) and "fudge" fileCnt somehow - not clear how. Possibly, one can change -d 1 to -d 5 in parameters for smbclient. Then the file names can be counted using /^\s*tar:\d+\s++++ (.*)$/, where $1 is the filename. However, this means dealing with a lot of noise from smbclient
3. Or change the code in BackupPC_dump not to rely on fileCnt as an indication of success, but use byteCnt instead

Any other ideas are greatly appreciated.

**Comment by ftrojahn** [comment] 2016-08-14 08:11
Hello,

besides from using rsync via vss instead, did you file this as a bug against
samba 4?

May be backuppc is not the only one missing this as a regression.

Best regards,
Falko

**Comment by ftrojahn** [comment] 2016-08-14 08:16
Btw: this is duplicate of #14 and there is a patch available.

**Comment by maksyms** [comment] 2016-08-14 08:32
Thanks a lot for that. I produced a different patch. I will compare the two.

I was not keen on bumping smbclient debug level to 5.

No, I have not logged it as a bug against smbclient. Not sure whether it is a bug - smbclient works fine and backs the files up... It is some counting logic in backuppc that relies on specific output...

**Comment by maksyms** [comment] 2016-08-14 08:38
@ftrojahn The patch supplied is ok, but it does make smbclient a lot chattier. May I suggest checking which one you guys prefer?

**Comment by craigbarratt** [comment] 2017-02-04 00:55
I've applied your fixes to 3.x.x (released in 3.3.2) and 4.x.

Thanks
Craig

**Closed by craigbarratt** 2017-02-04 00:55 UTC
