### ISSUE TITLE
v4 web interface still showing v4 rrdtool graphs

### ISSUE THREAD

**Issue by kwisatz** [backuppc/backuppc#491] opened 2023-02-15 18:23 UTC
After an upgrade from v3 to v4, the rrdtool graphs from v3 times are still being displayed on the new status page

![BackupPC-Server-Status](https://user-images.githubusercontent.com/237949/219118718-0149d5e2-5a5f-4c91-a612-c51f4feb6d4f.png)

**Comment by moisseev** [comment] 2023-02-16 06:42
Duplicate of #488

It's a Debian package bug. Please send bug report to the package maintainer.

**Closed** 2023-02-16 06:43 UTC
Labels: wontfix
