### ISSUE TITLE
on restore all files owner root

### ISSUE THREAD

**Issue by a1d3s** [backuppc/backuppc#171] opened 2017-12-05 07:44 UTC
Hi there , 
if i restore files from a webserver original owner webXXX clientXX and of i restore them , they are all owned by root root. 
backup runs as backuppc with sudo and rsync.
backuppc 4.1.3

**Comment by craigbarratt** [comment] 2017-12-24 00:30
What is $Conf{RsyncRestoreArgs} set to?  Can you include the first few lines of the RestoreLOG?

**Comment by a1d3s** [comment] 2018-01-02 06:58
`$Conf{RsyncRestoreArgs} = [
  '--numeric-ids',
  '--perms',
  '--owner',
  '--group',
  '-D',
  '--links',
  '--hard-links',
  '--times',
  '--block-size=2048',
  '--relative',
  '--ignore-times',
  '--recursive'
];
`

2018-01-02 07:56:49 restore started below directory / to host lxisp
2018-01-02 07:56:50 restore 3 complete (1 files, 5472 bytes, 0 dirs, 0 xferErrs)

**Comment by craigbarratt** [comment] 2018-01-02 07:05
$Conf{RsyncRestoreArgs} looks correct.  The RestoreLOG is the detailed transfer log - browse into the restore to view it (or use BackupPC_zcat).

We should first make sure it's really a restore problem, not a backup problem. Can you create a small tar restore file, and use tar tvf to see the user and group ids on the files in the tar file?  Are they correct?

Is there anything unusual about the file system you are restore the files to?

**Comment by a1d3s** [comment] 2018-01-02 07:55
Trimming /var/www/clients/client1/web417/web from remoteDir -> /
Wrote source file list to /var/lib/backuppc/pc/lxisp/.rsyncFilesFrom4185: /var/www/clients/client1/web417/web/login.php
Running: /usr/local/bin/rsync_bpc --bpc-top-dir /var/lib/backuppc --bpc-host-name lxisp --bpc-share-name / --bpc-bkup-num 97 --bpc-bkup-comp 3 --bpc-bkup-merge 97/3/4 --bpc-attrib-new --bpc-log-level 2 --rsync-path=sudo\ /usr/bin/rsync --numeric-ids --perms --owner --group -D --links --hard-links --times --block-size=2048 --relative --ignore-times --recursive --files-from=/var/lib/backuppc/pc/lxisp/.rsyncFilesFrom4185 / lxisp:/
This is the rsync child about to exec /usr/local/bin/rsync_bpc
bpc_attrib_backwardCompat: WriteOldStyleAttribFile = 0, KeepOldAttribFiles = 0
Done: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 1 filesTotal, 5472 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 0 inode

**Comment by a1d3s** [comment] 2018-01-02 08:11
rights 0rw-r--r-- root:root in the tar file

**Comment by a1d3s** [comment] 2018-01-02 08:29
This is the config.pl i used 


$ENV{'PATH'} = '/bin:/usr/bin';
delete @ENV{'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};
$Conf{ServerHost} = 'ftp2';
chomp($Conf{ServerHost});
$Conf{ServerPort} = -1;
$Conf{ServerMesgSecret} = '';
$Conf{MyPath} = '/bin';
$Conf{UmaskMode} = 23;
$Conf{WakeupSchedule} = [
  14,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23
];

$Conf{MaxBackups} = 2;
$Conf{MaxUserBackups} = 2;
$Conf{MaxPendingCmds} = 15;
$Conf{CmdQueueNice} = 10;
$Conf{MaxBackupPCNightlyJobs} = 2;
$Conf{BackupPCNightlyPeriod} = 1;
$Conf{MaxOldLogFiles} = 14;
$Conf{DfPath} = '/bin/df';
$Conf{DfCmd} = '$dfPath $topDir';
$Conf{SplitPath} = '/usr/bin/split';
$Conf{ParPath} = '/usr/bin/par2';
$Conf{CatPath} = '/bin/cat';
$Conf{GzipPath} = '/bin/gzip';
$Conf{Bzip2Path} = '/bin/bzip2';
$Conf{DfMaxUsagePct} = 95;
$Conf{DHCPAddressRanges} = [];
$Conf{BackupPCUser} = 'backuppc';
$Conf{TopDir} = '/var/lib/backuppc';
$Conf{ConfDir} = '/etc/BackupPC';
$Conf{LogDir} = '/var/log/BackupPC';
$Conf{RunDir} = '/var/run/BackupPC';
$Conf{InstallDir} = '/usr/local/BackupPC';
$Conf{CgiDir} = '/var/www/cgi-bin/BackupPC';
$Conf{BackupPCUserVerify} = '0';
$Conf{HardLinkMax} = 31999;
$Conf{PerlModuleLoad} = undef;
$Conf{ServerInitdPath} = undef;
$Conf{ServerInitdStartCmd} = '';
$Conf{FullPeriod} = '27.88';
$Conf{IncrPeriod} = '0.97';
$Conf{FullKeepCnt} = [
  4
];
$Conf{FullKeepCntMin} = 4;
$Conf{FullAgeMax} = 240;
$Conf{IncrKeepCnt} = 14;
$Conf{IncrKeepCntMin} = 4;
$Conf{IncrAgeMax} = 30;
$Conf{BackupsDisable} = 0;
$Conf{RestoreInfoKeepCnt} = 10;
$Conf{ArchiveInfoKeepCnt} = 10;
$Conf{BackupFilesOnly} = {};
$Conf{BackupFilesExclude} = {
  '*' => [
    '/proc',
    '/sys',
    '/var/lib/mysql'
  ]
};

$Conf{BlackoutBadPingLimit} = 3;
$Conf{BlackoutGoodCnt} = 7;
$Conf{BlackoutPeriods} = [
  {
    'hourEnd' => 18,
    'hourBegin' => 8,
    'weekDays' => [
      1,
      2,
      3,
      4
    ]
  }
];
$Conf{BackupZeroFilesIsFatal} = '0';
$Conf{XferMethod} = 'rsync';
$Conf{XferLogLevel} = 2;
$Conf{ClientCharset} = '';
$Conf{ClientCharsetLegacy} = 'iso-8859-1';
$Conf{SmbShareName} = [
  'C$'
];
$Conf{SmbShareUserName} = '';
$Conf{SmbSharePasswd} = '';
$Conf{SmbClientPath} = '/usr/bin/smbclient';
$Conf{SmbClientFullCmd} = '$smbClientPath \\\\$host\\$shareName $I_option -U $userName -E -d 1 -c tarmode\\ full -Tc$X_option - $fileList';
$Conf{SmbClientIncrCmd} = '$smbClientPath \\\\$host\\$shareName $I_option -U $userName -E -d 1 -c tarmode\\ full -TcN$X_option $timeStampFile - $fileList';
$Conf{SmbClientRestoreCmd} = '$smbClientPath \\\\$host\\$shareName $I_option -U $userName -E -d 5 -c tarmode\\ full -Tx -';
$Conf{TarShareName} = [
  '/'
];
$Conf{TarClientCmd} = '$sshPath -q -x -n -l root $host env LC_ALL=C $tarPath -c -v -f - -C $shareName+ --totals';
$Conf{TarFullArgs} = '$fileList+';
$Conf{TarIncrArgs} = '--newer=$incrDate+ $fileList+';
$Conf{TarClientRestoreCmd} = '$sshPath -q -x -l root $host env LC_ALL=C $tarPath -x -p --numeric-owner --same-owner -v -f - -C $shareName+';
$Conf{TarClientPath} = '/bin/tar';
$Conf{RsyncClientPath} = 'sudo /usr/bin/rsync';
$Conf{RsyncBackupPCPath} = '/usr/local/bin/rsync_bpc';
$Conf{RsyncShareName} = [
  '/'
];

$Conf{RsyncdClientPort} = 873;
$Conf{RsyncdUserName} = '';
$Conf{RsyncdPasswd} = '';
$Conf{RsyncArgs} = [
  '--numeric-ids',
  '--perms',
  '--owner',
  '--group',
  '-D',
  '--links',
  '--hard-links',
  '--times',
  '--block-size=2048',
  '--recursive'
];
$Conf{RsyncArgsExtra} = [];
$Conf{RsyncRestoreArgs} = [
  '--numeric-ids',
  '--perms',
  '--owner',
  '--group',
  '-D',
  '--links',
  '--hard-links',
  '--times',
  '--block-size=2048',
  '--relative',
  '--ignore-times',
  '--recursive'
];

$Conf{FtpShareName} = [
  ''
];
$Conf{FtpUserName} = '';
$Conf{FtpPasswd} = '';
$Conf{FtpPassive} = '1';
$Conf{FtpBlockSize} = 10240;
$Conf{FtpPort} = 21;
$Conf{FtpTimeout} = 120;
$Conf{FtpFollowSymlinks} = '0';
$Conf{ArchiveDest} = '/tmp';
$Conf{ArchiveComp} = 'gzip';
$Conf{ArchivePar} = '0';
$Conf{ArchiveSplit} = 0;
$Conf{ArchiveClientCmd} = '$Installdir/bin/BackupPC_archiveHost $tarCreatePath $splitpath $parpath $host $backupnumber $compression $compext $splitsize $archiveloc $parfile *';
$Conf{SshPath} = '/usr/bin/ssh';
$Conf{NmbLookupPath} = '/usr/bin/nmblookup';
$Conf{NmbLookupCmd} = '$nmbLookupPath -A $host';
$Conf{NmbLookupFindHostCmd} = '$nmbLookupPath $host';
$Conf{FixedIPNetBiosNameCheck} = '0';
$Conf{PingPath} = '/bin/ping';
$Conf{PingCmd} = '$pingPath -c 1 $host';
$Conf{PingMaxMsec} = 20;
$Conf{CompressLevel} = 3;
$Conf{ClientTimeout} = 72000;
$Conf{MaxOldPerPCLogFiles} = 12;
$Conf{DumpPreUserCmd} = undef;
$Conf{DumpPostUserCmd} = undef;
$Conf{DumpPreShareCmd} = undef;
$Conf{DumpPostShareCmd} = undef;
$Conf{RestorePreUserCmd} = undef;
$Conf{RestorePostUserCmd} = undef;
$Conf{ArchivePreUserCmd} = undef;
$Conf{ArchivePostUserCmd} = undef;
$Conf{UserCmdCheckStatus} = '0';
$Conf{ClientNameAlias} = undef;
$Conf{SendmailPath} = '/usr/sbin/sendmail';
$Conf{EMailNotifyMinDays} = '2.5';
$Conf{EMailFromUserName} = 'backuppc@backupserver';
$Conf{EMailAdminUserName} = 'reports@example.com';
$Conf{EMailUserDestDomain} = '';
$Conf{EMailNoBackupEverSubj} = undef;
$Conf{EMailNoBackupEverMesg} = undef;
$Conf{EMailNotifyOldBackupDays} = 7;
$Conf{EMailNoBackupRecentSubj} = undef;
$Conf{EMailNoBackupRecentMesg} = undef;
$Conf{EMailNotifyOldOutlookDays} = 5;
$Conf{EMailOutlookBackupSubj} = undef;
$Conf{EMailOutlookBackupMesg} = undef;
$Conf{EMailHeaders} = 'MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
';
$Conf{CgiAdminUserGroup} = 'backuppc';
$Conf{CgiAdminUsers} = 'backuppc';
$Conf{CgiURL} = 'http://backuppc/cgi-bin/BackupPC/BackupPC_Admin';
$Conf{Language} = 'en';
$Conf{CgiUserHomePageCheck} = '';
$Conf{CgiUserUrlCreate} = 'mailto:%s';
$Conf{CgiDateFormatMMDD} = 2;
$Conf{CgiNavBarAdminAllHosts} = '1';
$Conf{CgiSearchBoxEnable} = '1';
$Conf{CgiNavBarLinks} = [
  {
    'link' => '?action=view&type=docs',
    'lname' => 'Documentation',
    'name' => undef
  },
  {
    'lname' => undef,
    'link' => 'https://github.com/backuppc/backuppc/wiki',
    'name' => 'Wiki'
  },
  {
    'name' => 'Github',
    'link' => 'https://backuppc.github.io/backuppc',
    'lname' => undef
  }
];
$Conf{CgiStatusHilightColor} = {
  'Disabled_AllBackupsDisabled' => '#d1d1d1',
  'Reason_no_ping' => '#ffff99',
  'Reason_backup_done' => '#ccffcc',
  'Status_backup_in_progress' => '#66cc99',
  'Disabled_OnlyManualBackups' => '#d1d1d1',
  'Reason_backup_failed' => '#ffcccc',
  'Reason_backup_canceled_by_user' => '#ff9900'
};
$Conf{CgiHeaders} = '<meta http-equiv="pragma" content="no-cache">';
$Conf{CgiImageDir} = '/var/www/htdocs/BackupPC';
$Conf{CgiExt2ContentType} = {};
$Conf{CgiImageDirURL} = '/BackupPC';
$Conf{CgiCSSFile} = 'BackupPC_stnd.css';
$Conf{CgiUserConfigEditEnable} = '1';
$Conf{CgiUserConfigEdit} = {
  'RsyncClientPath' => '0',
  'SmbShareUserName' => '1',
  'TarClientPath' => '0',
  'EMailNotifyMinDays' => '1',
  'NmbLookupFindHostCmd' => '0',
  'RsyncShareName' => '1',
  'EMailNoBackupRecentSubj' => '1',
  'RsyncdClientPort' => '1',
  'FullKeepCnt' => '1',
  'ArchivePar' => '1',
  'EMailNoBackupEverSubj' => '1',
  'ArchiveDest' => '1',
  'SmbClientIncrCmd' => '0',
  'FullAgeMax' => '1',
  'IncrAgeMax' => '1',
  'IncrKeepCnt' => '1',
  'RsyncRestoreArgs' => '1',
  'SmbSharePasswd' => '1',
  'DumpPreUserCmd' => '0',
  'RsyncdUserName' => '1',
  'FillCycle' => '0',
  'EMailNotifyOldBackupDays' => '1',
  'EMailUserDestDomain' => '1',
  'ClientNameAlias' => '1',
  'RsyncArgsExtra' => '1',
  'PingMaxMsec' => '1',
  'BackupZeroFilesIsFatal' => '1',
  'EMailNoBackupEverMesg' => '1',
  'FtpBlockSize' => '1',
  'PingCmd' => '0',
  'TarClientRestoreCmd' => '0',
  'DumpPreShareCmd' => '0',
  'RsyncSshArgs' => '0',
  'RsyncdPasswd' => '1',
  'CompressLevel' => '1',
  'BackupFilesOnly' => '1',
  'EMailNoBackupRecentMesg' => '1',
  'FtpPasswd' => '1',
  'BlackoutPeriods' => '1',
  'ClientCharset' => '1',
  'UserCmdCheckStatus' => '0',
  'ClientTimeout' => '1',
  'IncrPeriod' => '1',
  'DumpPostUserCmd' => '0',
  'TarIncrArgs' => '1',
  'RestorePreUserCmd' => '0',
  'FullKeepCntMin' => '1',
  'EMailAdminUserName' => '1',
  'TarShareName' => '1',
  'FullPeriod' => '1',
  'ClientCharsetLegacy' => '1',
  'FtpFollowSymlinks' => '1',
  'IncrKeepCntMin' => '1',
  'RsyncdAuthRequired' => '1',
  'SmbClientRestoreCmd' => '0',
  'FtpTimeout' => '1',
  'ArchivePostUserCmd' => '0',
  'FtpShareName' => '1',
  'XferMethod' => '1',
  'ArchiveComp' => '1',
  'FtpUserName' => '1',
  'BlackoutBadPingLimit' => '1',
  'RsyncArgs' => '1',
  'MaxOldPerPCLogFiles' => '1',
  'TarFullArgs' => '1',
  'FixedIPNetBiosNameCheck' => '1',
  'TarClientCmd' => '0',
  'EMailOutlookBackupSubj' => '1',
  'EMailFromUserName' => '1',
  'FtpPort' => '1',
  'ArchiveInfoKeepCnt' => '1',
  'EMailOutlookBackupMesg' => '1',
  'SmbShareName' => '1',
  'ArchiveClientCmd' => '0',
  'ArchiveSplit' => '1',
  'RsyncFullArgsExtra' => '0',
  'EMailHeaders' => '1',
  'RestoreInfoKeepCnt' => '1',
  'FtpRestoreEnabled' => '1',
  'EMailNotifyOldOutlookDays' => '1',
  'BackupsDisable' => '1',
  'XferLogLevel' => '1',
  'RestorePostUserCmd' => '0',
  'ArchivePreUserCmd' => '0',
  'SmbClientFullCmd' => '0',
  'NmbLookupCmd' => '0',
  'DumpPostShareCmd' => '0',
  'BlackoutGoodCnt' => '1',
  'RefCntFsck' => '0',
  'BackupFilesExclude' => '1'
};
$Conf{FillCycle} = 0;
$Conf{Ping6Path} = '/bin/ping6';
$Conf{PoolSizeNightlyUpdatePeriod} = 0;
$Conf{PoolV3Enabled} = '0';
$Conf{RefCntFsck} = 0;
$Conf{RrdToolPath} = '/usr/bin/rrdtool';
$Conf{RsyncFullArgsExtra} = [];
$Conf{RsyncSshArgs} = [];
$Conf{SCGIServerPort} = -1;

**Comment by craigbarratt** [comment] 2018-01-02 21:42
The tar file test suggests that the backup is stored with 0/0 gid/uid, so perhaps the problem is with the backup, rather than restore.

Can you look in the most recent full backup XferLOG file and see what permissions are transferred for that file?  You might need to increase the XferLogLevel to 2 or 3 and then do a new full backup to see permissions on unchanged files.

**Comment by craigbarratt** [comment] 2018-01-20 23:09
Just following up on my previous questions.  Please look in the XferLOG file to see what uid/gid is transferred when you do a backup.

**Comment by craigbarratt** [comment] 2018-01-26 01:39
Closing due to no responses.

**Closed by craigbarratt** 2018-01-26 01:39 UTC
