### ISSUE TITLE
Incomplete XferLog

### ISSUE THREAD

**Issue by nonamessh** [backuppc/backuppc#236] opened 2018-11-15 09:16 UTC
Hello,

can someone confirm, that the XferLogs are incomplete. It's probably related to this error (showing up after running "BackupPC/bin/BackupPC_zcat XferLOG.XY.z":

`BackupPC/bin/BackupPC_zcat: can't uncompress XferLOG.XY.z`

I figure that somehow the last part of the logfile can't be uncompressed causing the issue.

**Comment by craigbarratt** [comment] 2018-11-16 10:31
If a backup exit abnormally (eg, killed) then the XferLOG file might not have the last part flushed correct.

Does that command generate any output at all?

**Comment by nonamessh** [comment] 2018-11-16 10:44
Hi,
thanks for the quick response. Sorry for not being clearer when I first submitted the issue.
 I get basically the whole log, just the last couple of lines are missing. I guess that the final "block" gets somehow corrupted.
The backups themselves run thru without a problem and I think all of my logs are affected by this issue.

**Comment by craigbarratt** [comment] 2018-11-16 10:56
Hmm, that is strange.  Can you email me a (small) XferLOG.z file?

What versions of BackupPC, backuppc-xs, perl and Compress::Zlib are you running?

**Comment by nonamessh** [comment] 2018-11-16 11:19
Sure, just sent you an example Xferlog.

BackupPC 4.2.1
BackupPC-XS 0.57
Perl 5.24.1
Compress::Zlib 1.2.8

**Comment by craigbarratt** [comment] 2018-11-17 07:41
It's a bug caused by the exit() right after DumpPostUserCmd fails to exec().  That causes the child process to flush the XferLOG file, which it shouldn't do.

The fix is to replace the exit() on line 1238 in lib/BackupPC/Lib.pm with POSIX::_exit(), which will also need a "use POSIX qw(_exit);" near the top.  I'll commit a patch this weekend.

**Comment by nonamessh** [comment] 2018-11-17 10:20
Perfect, thank you very much.

**Comment by craigbarratt** [comment] 2018-11-17 18:53
Pushed fix 2045209.

**Closed by craigbarratt** 2018-11-17 18:53 UTC
