### ISSUE TITLE
Installer misses installing libs

### ISSUE THREAD

**Issue by johanehnberg** [backuppc/backuppc#45] opened 2017-01-28 07:37 UTC
After recent changes, the installer no longer installs the libraries.

The error when starting BackupPC is:
Starting backuppc: Can't locate BackupPC/Lib.pm in @INC (you may need to install the BackupPC::Lib module) (@INC contains: /usr/local/BackupPC/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/BackupPC/bin/BackupPC line 57.
BEGIN failed--compilation aborted at /usr/local/BackupPC/bin/BackupPC line 57.

From the mailing list:
On 01/27/2017 08:01 PM, Les Mikesell wrote:
> On Fri, Jan 27, 2017 at 11:38 AM, Kent Tenney <ktenney@gmail.com> wrote:
>> https://github.com/backuppc/backuppc/wiki/Installing-BackupPC-4-from-git-on-Ubuntu-Xenial-16.04-LTS
>>
>> After running the wiki script,
>>  /usr/loca/BackupPC/bin/BackupPC
>> fails with
>> Can't locate BackupPC/Lib.pm in @INC (you may need to install the
>> BackupPC::Lib module) (@INC contains: /usr/local/BackupPC/lib /etc/perl
>> /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1
>> /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5
>> /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22
>> /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at
>> /usr/local/BackupPC/bin/BackupPC line 57.
>> BEGIN failed--compilation aborted at /usr/local/BackupPC/bin/BackupPC line
>> 57.
>>
>> It seems the lib files weren't installed,
>> # tree /usr/local/BackupPC/lib
>> /usr/local/BackupPC/lib/
>> ├── BackupPC
>> │   ├── CGI
>> │   ├── Config
>> │   ├── Lang
>> │   ├── Storage
>> │   ├── Xfer
>> │   └── Zip
>> └── Net
>>     └── FTP
> 
> I haven't installed v4 yet so I can't be more specific, but what you
> are showing are just the directories in /usr/local/BackupPC/lib/ which
> seem to at least exist, but your error is about a particular file.
> The @INC list is the search path where perl will try to find it.
> Does /usr/local/BackupPC/lib/BackupPC/Lib.pm exist, and if so is it
> and the path to it readable by the backuppc user?
> 

Hi Kent and Les,

Thanks for the report! I maintain the mentioned instructions, and can confirm this error.

It seems something has changed in the latest code, and while the installer says:

  Installing library in /usr/local/BackupPC/lib

The lib folders remain empty. The exit status is also OK, so the installer may not even see the error. As such it is a bug in the build automation.

The lib folder was changed a few days ago by Craig Barratt, mentioning significant changes.

I will create an issue with these notes, and link it to the wiki.

Best regards,
Johan Ehnberg

**Comment by ktenney** [comment] 2017-01-30 14:56
The error msg has changed. 
commit edbd1a4613e0125ed65372738abff935230db075

when the script executes 'makeDist ...'

Unexpected Conf var RefCntFsck in bin/BackupPC_refCountUpdate
Exiting because of errors

**Comment by gnoling** [comment] 2017-02-02 16:10
This seems to be caused by a sanity check problem finding regarding line 245 in bin/BackupPC_refCountUpdate. The variable inside the comment is what's causing the Unexpected Conf failure, removing the variable (just remove the cash symbol inside the comment) temporarily resolves the error.

**Comment by ktenney** [comment] 2017-02-02 19:11
This indeed allows makeDist to complete without error, however
there still are no files under /usr/local/BackupPC/lib

Thanks,
Kent

**Comment by gnoling** [comment] 2017-02-02 19:18
I didn't go through the code enough to figure out that issue, but it's ultimately caused by makeDist populating ./configure.pl with the wrong files under @ConfigureLibList. I dug enough to see that it should be this...

```
my @ConfigureLibList = qw(
    lib/BackupPC/Config/Meta.pm
    lib/BackupPC/DirOps.pm
    lib/BackupPC/Lib.pm
    lib/BackupPC/Storage.pm
    lib/BackupPC/View.pm
    lib/BackupPC/Xfer/Archive.pm
    lib/BackupPC/Xfer/Ftp.pm
    lib/BackupPC/Xfer/Protocol.pm
    lib/BackupPC/Xfer/Rsync.pm
    lib/BackupPC/Xfer/Smb.pm
    lib/BackupPC/Xfer/Tar.pm
    lib/BackupPC/Xfer.pm
    lib/BackupPC/Zip/FileMember.pm
    lib/Net/FTP/AutoReconnect.pm
    lib/Net/FTP/RetrHandle.pm
    lib/BackupPC/CGI/AdminOptions.pm
    lib/BackupPC/CGI/Archive.pm
    lib/BackupPC/CGI/ArchiveInfo.pm
    lib/BackupPC/CGI/Browse.pm
    lib/BackupPC/CGI/DirHistory.pm
    lib/BackupPC/CGI/EditConfig.pm
    lib/BackupPC/CGI/EmailSummary.pm
    lib/BackupPC/CGI/GeneralInfo.pm
    lib/BackupPC/CGI/HostInfo.pm
    lib/BackupPC/CGI/Lib.pm
    lib/BackupPC/CGI/LOGlist.pm
    lib/BackupPC/CGI/Queue.pm
    lib/BackupPC/CGI/ReloadServer.pm
    lib/BackupPC/CGI/Restore.pm
    lib/BackupPC/CGI/RestoreFile.pm
    lib/BackupPC/CGI/RestoreInfo.pm
    lib/BackupPC/CGI/RSS.pm
    lib/BackupPC/CGI/StartServer.pm
    lib/BackupPC/CGI/StartStopBackup.pm
    lib/BackupPC/CGI/StopServer.pm
    lib/BackupPC/CGI/Summary.pm
    lib/BackupPC/CGI/View.pm
    lib/BackupPC/Lang/cz.pm
    lib/BackupPC/Lang/de.pm
    lib/BackupPC/Lang/en.pm
    lib/BackupPC/Lang/es.pm
    lib/BackupPC/Lang/fr.pm
    lib/BackupPC/Lang/it.pm
    lib/BackupPC/Lang/ja.pm
    lib/BackupPC/Lang/nl.pm
    lib/BackupPC/Lang/pl.pm
    lib/BackupPC/Lang/pt_br.pm
    lib/BackupPC/Lang/ru.pm
    lib/BackupPC/Lang/uk.pm
    lib/BackupPC/Lang/zh_CN.pm
    lib/BackupPC/Storage/Text.pm
    );
```

But what gets generated is the same as @ConfigureBinList, which it shouldn't be. Replacing the section with the above (manually) worked for me; then just run the ./configure.pl command from the tutorial again. Make the change I mentioned *after* makeDist, it's okay if you just re-run configure.pl again from trying before.

**Comment by ktenney** [comment] 2017-02-02 21:49
With that change and
chown -R backuppc:backuppc

/usr/local/BackupPC/bin/BackupPC

will start!

Now to get the web interface working ...

Thanks,
Kent

**Comment by craigbarratt** [comment] 2017-02-03 02:26
This should be fixed now.  makeDist runs cleanly, and configure.pl now has the correct library list after makeDist runs.

**Closed by craigbarratt** 2017-02-03 02:26 UTC
